### ISSUE TITLE
Add student group explanations

### ISSUE THREAD

**Issue by prairir** [UWindsorCSS/wiki#70]
#### Describe Problem
There are a ton of groups on campus like CSS, CSC, Eng society, Sci Soc, etc. 
#### Suggest Solution
A glossary of student groups with a quick blurb about what they do, what they want to do, and how to get involved(with links and stuff) would round out whats going on

#### Additional Details
It may be a good idea to reach out to student groups so they can write it themselves

**Comment by benchittle** [comment]
So there's a looooot of clubs, I've put a few scattered ones here just to start it off but I think we should separate the big clubs from the small ones, or organize them somehow. 

## A scattered list of clubs...
- Computer Science Society [css@uwindsor.ca](mailto:css@uwindsor.ca) and https://css.uwindsor.ca/

### From https://www.uwindsor.ca/engineering/student-groups
- Engineering Student Society [engsoc@uwindsor.ca](mailto:engsoc@uwindsor.ca) and https://linktr.ee/windsor_engsoc (main site is under construction atm)
- Arduino Club https://www.instagram.com/uwindsorarduino/
- AI Club https://discord.com/invite/mGmrU7Gr6N
- Association of Energy Engineers Windsor Student Chapter (AEE-WSC) https://www.aeecenter.org/listing/university-of-windsor-student-chapter/
- ... and many more from that site, though many links seem to be outdated

### Other
- Jack.org UWindsor [jackorg@uwindsor.ca](mailto:jackorg@uwindsor.ca) and https://www.facebook.com/jackorguwindsor/ (they're a mental health advocacy group)
- Bachelor of Arts and Science Association (BASA) [basauwindsor@gmail.com](mailto:basauwindsor@gmail.com) and https://www.instagram.com/basa.uwindsor/ (I'm not sure if they're a ratified club, but they're a club for the Bachelor of Arts and Sciences program that my gf was a part of. They're only open to BASA program students though)
- UWindsor Wellness Livestream [livestreamwellness@uwindsor.ca](mailto:livestreamwellness@uwindsor.ca) and https://www.instagram.com/uwinwellnesslive/ (wellness group)

**Comment by Lillliant** [comment]
I found some more student groups from the UWSA hub, and I'll try to look for more once the UWindsor site is back up again. There were around 130+ clubs in the UWSA alone, but since a lot of the clubs don't have any contact info listed, I just jot down ones that have emails or social medias.

I'm thinking of organizing these by faculties/departments in the final wiki article, but there are a lot of clubs outside of these categories. Would it be better to group them alphabetically?

# societies
- computer science society: css@uwindsor.ca
- science society: scisoc@uwindsor.ca
- creative arts society: cassociety@uwindsor.ca
- dramatic arts society: clubsoda@uwindsor.ca
- education society: edsociety@uwindsor.ca
- engineering students' society: engsoc@uwindsor.ca
- human kinetics society: hkspres@uwindsor.ca
- nursing society: uwinnursingsoc@gmail.com
- odette commerce society: ocs@uwindsor.ca
- political science society: usirpsuwin@gmail.com
- pre-dental society: uwpds@uwindsor.ca
- pre-law society: plss@uwindsor.ca
- pre-med society: uofwpremedsociety@gmail.com
- pre-optometry society: no email but has insta
- pre-pharmacy society: no email but has insta
- pre-physician assistant society: no email but has insta

# student associations and unions
- uwsa: uwsa@uwindsor.ca
- opus: opus@uwindsor.ca
- bangladesh-windsor student association: no email but this might be them: https://www.facebook.com/bsawindsor/?ref=page_internal
- basa (bachelor of arts & science student association): basauwindsor@gmail.com
- behaviour cognition and neuroscience student association: bcnsa@uwindsor.ca
- forensic student association: uwinfsa@hotmail.com
- indian student association: uwisa@uwindsor.ca
- math & stats student association: mssa@uwindsor.ca
- muslim student association: msa@uwindsor.ca
- pakistani student association: found a twitter but hasn't been updated since 2015
- work integrated learning association: wila.uwin@gmail.com
- biomed sciences students association: has insta
- alzheimer's awareness association: aaa@uwindsor.ca
- association of serbian student philanthropists: serbs@uwindsor.ca
- catholic students' association: has a website but can't access it right now - https://www.uwindsor.ca/campusministry/462/catholic-students-association
- communication students' association: csacmf@uwindsor.ca
- criminology association: uwocrim@uwindsor.ca
- desi dance association: desidance@uwindsor.ca
- disability studies students' association: dssa@uwindsor.ca
- firearms association: uofwfa@gmail.com
- odette human resources association: ohra@uwindsor.ca
- odette marketing association: oma@uwindsor.ca
- psychology students' association: psa@uwindsor.ca
- sikh student association: uwinssa@gmail.com
- thaqalayn muslim association: tmauwin@gmail.com
- uwindsor undergraduate mock trial associationuwinmocktrial@gmail.com
- women's justice and empowerment association: wjea2020@gmail.com
- biology students' union: bsu@uwindsor.ca

# clubs and other student groups

## faculty of science
- physics club: physclub@uwindsor.ca
- general science club: has insta
- artificial intelligence club: hosted events but has no public contact info
- videogame design club: has a discord but no public contact info
- undergrad chem & biochem club: ugcc@uwindsor.ca 
- USCI network: has uwindsor site - http://www.uwindsor.ca/science/327/usci-network
- undergrad chem club: has insta - https://www.instagram.com/uwinchemclub/

## faculty of engineering
- CITE: has a uwindsor website - https://www.uwindsor.ca/engineering/research/500/cite-events-news
- arduino club: uwinarduino@gmail.com
- women in engineering: wie@uwindsor.ca
- wire (women in renewable engineering): has twitter - https://twitter.com/WiRE_Canada/status/1327298339881308160

## fahss
- anthrozoology club: uwindsoranthrozoology@gmail.com
- uwin reach: this uwindsor webpage might be them - https://www.uwindsor.ca/fahss/online-advising/reach
- philosophy club: has a FB page but no general contact info for club execs - https://www.facebook.com/groups/UWindsorPhilosophy/about

## political/activist
- palestinian solidarity group: windsorpsg@gmail.com
- model united nations (WINMUN): winmunhsc@gmail.com
- WEStudents united: westudentsuwindsor@gmail.com
- uwindsor conservatives: uwindsortory@gmail.com
- students against ford: has FB page that might be them - https://www.facebook.com/DefeatFord

## charity/non-profit
- palestine children’s relief fund: no email but has insta
- music box children's charity: musicbox.uwindsor@gmail.com
- jack.org: jackorg@uwindsor.ca
- crafting for a cure: crafting@uwindsor.ca
- kind minds foundation: has FB page - https://www.facebook.com/kindmindsofficial/
- uwindsor nextgen lifeline blood club: has a FB page that might be them - https://www.facebook.com/UWindsorBloodClub/
- the youth connection: theyouthconnectionwindsor@gmail.com
- the listening party: thelisteningpartyuow@gmail.com
- students supporting seniors: has insta https://www.instagram.com/uwindsorsss/?hl=en
- students offering support: windsor.pres@studentsofferingsupport.org
- stem cell club: has FB page - https://www.facebook.com/uwinstemcell/
- relay for life: has FB page - https://www.facebook.com/Uwindsorrelay/
- friends of MSF: fomsf@uwindsor.ca

## cultural
- kculture: has insta
- caribbean african organization of students: caos@uwindsor.ca

## med/healthcare
- medlife: uwinmedlife@uwindsor.ca
- heart and stroke: heartandstroke@uwindsor.ca
- icure: has insta https://www.instagram.com/uwicure/
- CUCOH: has insta https://www.instagram.com/cucohwindsor/?hl=en
- canadian students for sensible drug policy: uwindsor@cssdp.org

## sports
- windsor equestrian team: lancers.equestrian@gmail.com
- chess club: has insta https://www.instagram.com/uwinchess/?hl=en
- uwinesports: has twitch - https://www.twitch.tv/uwinesports
- board game club: ebrahimo@uwindsor.ca
- uskate windsor: uskate@uwindsor.ca
- tennis club: has insta - https://www.instagram.com/uwindsortennisclub/?hl=en

## other/uncategorized
- power to change: p2c@uwindsor.ca
- pawsitively plant based: pawsitively.plant.based@gmail.com
- parks campus club: uwinparkscampusclub@gmail.com
- omicron nu optimist club: has FB page 
- making it awkward: MIAwindsor16@gmail.com
- little kindness: has insta
- lancer aerosports club: lanceraerosports@gmail.com
- jull environment club: https://www.uwindsor.ca/science/environment/592/jull-club
- hosa: hosauwin@gmail.com
- her campus: hc.uwindsor@hercampus.com
- golden future south africa: goldenfuture.windsor@gmail.com
- girlup: girlupuwindsor@gmail.com
- formula electric SAE: windsorfsae@gmail.com (https://www.windsorfsae.com/)
- FIRST alumni: https://www.uwinfirst.ca/
- enactus uwindsor: executive@enactuswindsor.com
- crossroads ACF: cross.roadsj7@gmail.com
- circle k international: uwindsor.cki@gmail.com
- windsor anime institute: windsor.anime.institute@gmail.com
- volunteer international students assistance (VISA): visa@uwindsor.ca
- uwinLoop: has FB page - https://www.facebook.com/uWinLoop/
- united fandoms: unitedfandoms2020@gmail.com
- together for the best: togetherforthebest6@gmail.com
- SWAM: windsor@swamcanada.ca
- share a smile: shareasmile@uwindsor.ca
- project playalot: has FB page - https://www.facebook.com/ProjectPlayalot
- pride club: has FB page - https://www.facebook.com/uwinprideclub/posts
- windsor actuarial club: has FB page - https://www.facebook.com/WindsorActuarialClub/
- uwindsor welcomes nursing students: has uwindsor page mentioning them but no public info - https://www.uwindsor.ca/nursing/489/incoming-year-1-bscn-students

**Comment by Lillliant** [comment]
Also, this is the template that I wrote for contacting student groups. Does this look okay?

```
Hello,

The Computer Science Society is working on a student wiki that will go live in September 2022. We are working to make a glossary of the students groups on campus. We are hoping that your organization can write a short paragraph that briefly describes your goals and visions. Here are some questions if you are interested in writing a paragraph:

•	What does your organization do on the campus? What goals and visions do you have for the organization?
•	What is a current event/project that you would like to showcase? Do you have any events/projects planned for the future?
•	What are the ways students can get involved with your organization? What kind of roles do they serve, or what kind of tasks do they perform?
•	Is there a regular recruitment routine? If so, what is the timeline/platform of which this routine takes place on?
•	What are some platforms that your organizations are active on?
•	If a student has any questions about your organization, what platforms should they reach you on?

Sincerely,
Computer Science Society Developers Team
```

**Comment by prairir** [comment]
many people believe the golden key honour society is a scam. https://blogs.ubc.ca/katyatubc/2011/09/20/golden-key-honour-society-scam/ there are also tons of other examples of people saying so if you google it

**Comment by prairir** [comment]
The email template looks great. I think it is best if we send the emails from the `css@uwindsor.ca` email

**Comment by Lillliant** [comment]
> many people believe the golden key honour society is a scam. https://blogs.ubc.ca/katyatubc/2011/09/20/golden-key-honour-society-scam/ there are also tons of other examples of people saying so if you google it

Wow, didn't know about that. I'll take it off the list

**Comment by Lillliant** [comment]
> The email template looks great. I think it is best if we send the emails from the `css@uwindsor.ca` email

I think so too!

**Comment by prairir** [comment]
I will send out the emails from `css@uwindsor.ca` when the outage is over. I think its best to wait incase they have documents or anything that they would want to share but are unable because of the outage.

**Comment by jere-mie** [comment]
just bumping this

**Comment by Dante-Masciotra** [comment]
After careful consideration and discussion, we have come to the conclusion that this resource does not align with the purpose of our wiki. Moving forward, we intend to focus the wiki exclusively on information relevant to the CSS and CS courses, as well as other helpful documents. If you believe that this section is necessary, we are open to hear your thoughts.
