### ISSUE TITLE
Add first year guide

### ISSUE THREAD

**Issue by benchittle** [UWindsorCSS/wiki#86]
#### Describe Problem
Entering university is a busy and stressful time for new students, and they are usually being blasted with new information. While there is a lot of useful information out there for new students, it can be difficult to find it, especially when it is spread across multiple sites and articles.

#### Suggest Solution
Put together a First Year Guide *specifically for new students in a computer science program*. 

#### Additional Details
The scope of the guide shouldn't get too big. It should focus on what we think is *necessary to succeed* during the weeks leading up to the first day of classes and the beginning of the first term. Everything beyond that should be bonus / brief mentions and links to further reading. 

Some topics to cover:
- Briefly cover general info for all new students (activating UWin account, student.uwindsor.ca, links to resources, etc.)
- What courses to pick for the first term
- Necessary software: getting a code editor, C compiler, basics of bash/sh, ssh'ing to CS servers vs nomachine, WSL for Windows users
- Bonus: Getting a GitHub account and resources to learn Git and GitHub
- Bonus: Setting up a LinkedIn account, linking it to UWindsor account
- Bonus: Hackathons, and the importance of making side projects

Resources:
- https://www.uwindsor.ca/science/computerscience/1294/welcome-school-computer-science
- current wiki articles

More suggestions welcome!

**Comment by Lillliant** [comment]
It would also be a good idea to add some basic information about finance (how paying tuition works, where people can seek financial help, etc.). I think a glossary of terms and what they mean (ex. financial drop date, voluntary withdrawal, major vs. cumulative average, etc.) would be helpful for the first-years too.

**Comment by Lillliant** [comment]
Here's some resources that might be useful:

**general guide**

- [cs welcome booklet](https://www.uwindsor.ca/science/computerscience/sites/uwindsor.ca.science.computerscience/files/windsor_welcome_booklet_2021.pdf)
- [University Guide by Jose Alba](https://docs.google.com/document/d/1OaK6moqKLeFBVVfZ1gJAYCV_DsuvNxHvRAykeAMUhYU/edit?fbclid=IwAR2vBoM9rOHdwhU5ueukdeYdEeXe-slz2BiF5kZBZ0NF14SjbtuLDhl4jpU)
- [uwindsor future students page](https://future.uwindsor.ca/?elqTrackId=02bedbef784241edba1ad7685efcbc0b&elq=00000000000000000000000000000000&elqaid=599&elqat=2&elqCampaignId=&elqcst=272&elqcsid=43)

**technical info for new students**
- https://www.uwindsor.ca/itservices/getting-started-students
- https://www.uwindsor.ca/science/computerscience/1294/welcome-school-computer-science

**course planning**
- wiki's article ("Jose's recommended course sequence" in PR #87)
- https://future.uwindsor.ca/plan-your-program#course-selection
- https://www.uwindsor.ca/registrar/sites/uwindsor.ca.registrar/files/uwinsiteregguide-update-april28-2022.pdf
- [registration guide](https://ask.uwindsor.ca/app/answers/detail/a_id/550/kw/registration%20resources?elqTrackId=92722437558f4856919ad085f07a46d6&elq=00000000000000000000000000000000&elqaid=596&elqat=2&elqCampaignId=&elqcst=272&elqcsid=99)

**hackathons**
- https://mlh.io/seasons/2023/events
- [hub section on hackathon](https://github.com/UWindsorCSS/hub/blob/master/app/views/markdown_pages/GUIDE.markdown#hackathons)

**linkedin learning**
- https://uwindsor.teamdynamix.com/TDClient/Requests/ServiceDet?ID=12233
(this site isn't working for some students, so there might be site issue/eligibility requirement)

**git & github**
- https://docs.github.com/en/get-started/quickstart/hello-world

**necessary software**
- http://help.cs.uwindsor.ca/ - this wiki is down right now due to outage, but I'm pretty sure it had guides on nomachine, bitvise, putty, etc.
- [Kelly's guide on vscode](https://www.youtube.com/watch?v=XPrwuvzFREU)
- [Kelly's guide on ssh in vscode](https://www.youtube.com/watch?v=KJYt-vTTvUE)

**finance**
- https://www.uwindsor.ca/studentawards/osap
- https://www.uwindsor.ca/finance/784/payment-options

**Comment by jere-mie** [comment]
done, ty Ben 😎
